// This is currently a mix of the interestType codelists from v0.3 and earlier
export default {
  shareholding: 'Shareholding',
  votingRights: 'Voting rights',
  appointmentOfBoard: 'Appointment of board',
  otherInfluenceOrControl: 'Other influence or control',
  seniorManagingOfficial: 'Senior managing official',
  settlor: 'Settlor',
  trustee: 'Trustee',
  protector: 'Protector',
  beneficiaryOfLegalArrangement: 'Beneficiary of a legal arrangement',
  rightsToSurplusAssetsOnDissolution: 'Rights to surplus assets on dissolution',
  rightsToProfitOrIncome: 'Rights to receive profits or income',
  rightsGrantedByContract: 'Rights granted by contract',
  conditionalRightsGrantedByContract: 'Conditional rights granted by contract',
  controlViaCompanyRulesOrArticles: 'Control via company rules or articles',
  controlByLegalFramework: 'Control by legal framework',
  boardMember: 'Board member',
  boardChair: 'Board chair',
  unknownInterest: 'Unknown interest',
  unpublishedInterest: 'Unpublished interest',
  enjoymentAndUseOfAssets: 'Enjoyment and use of assets',
  rightToProfitOrIncomeFromAssets: 'Right to profit or income from assets',
  'voting-rights': 'Voting rights',
  'appointment-of-board': 'Appointment of board',
  'other-influence-or-control': 'Other influence or control',
  'senior-managing-official': 'Senior managing official',
  'beneficiary-of-legal-arrangement': 'Beneficiary of a legal arrangement',
  'rights-to-surplus-assets-on-dissolution': 'Rights to surplus assets on dissolution',
  'rights-to-profit-or-income': 'Rights to receive profits or income',
  'rights-granted-by-contract': 'Rights granted by contract',
  'conditional-rights-granted-by-contract': 'Conditional rights granted by contract',
  'control-via-company-rules-or-articles': 'Control via company rules or articles',
  'control-by-legal-framework': 'Control by legal framework',
  'board-member': 'Board member',
  'board-chair': 'Board chair',
  'unknown-interest': 'Unknown interest',
  'unpublished-interest': 'Unpublished interest',
  'enjoyment-and-use-of-assets': 'Enjoyment and use of assets',
  'right-to-profit-or-income-from-assets': 'Right to profit or income from assets',
  'influence-or-control': 'Influence or control',
  'settlor-of-trust': 'Settlor of trust',
  'trustee-of-trust': 'Trustee of a trust',
  'protector-of-trust': 'Protector of a trust',
  'beneficiary-of-trust': 'Beneficiary of a trust',
  'other-influence-or-control-of-trust': 'Other influence or control of a trust',
  'rights-to-surplus-assets': 'Rights to surplus assets',
};
