version: 2.1
orbs:
  node: circleci/node@4.0.0
  slack: circleci/slack@3.4.2
jobs:
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run lint
      - slack/status:
        fail_only: true
        webhook: webhook
workflows:
  lint:
    jobs:
      - lint
